version: 2

project_name: cee-exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: cee-exporter
    main: ./cmd/cee-exporter
    binary: cee-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: cee-exporter
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - id: cyclonedx-gomod
    artifacts: any
    cmd: cyclonedx-gomod
    args:
      - mod
      - -licenses
      - -json
      - -output
      - $document
      - ../
    documents:
      - "{{ .ProjectName }}_{{ .Version }}.sbom.cdx.json"

changelog:
  use: github-native

release:
  prerelease: auto
